-- CLINICA APP Schema PostgreSQL
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE TYPE perfil_usuario AS ENUM ('paciente','medico','recepcionista','admin');
CREATE TYPE status_agendamento AS ENUM ('pendente','confirmado','realizado','cancelado','faltou');
CREATE TYPE status_exame AS ENUM ('solicitado','agendado','coletado','em_analise','disponivel','entregue');
CREATE TYPE tipo_notificacao AS ENUM ('push','whatsapp','sms','email');
CREATE TYPE status_notificacao AS ENUM ('pendente','enviada','falhou');
CREATE TYPE sexo AS ENUM ('M','F','outro');
CREATE TABLE usuarios(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),firebase_uid TEXT UNIQUE NOT NULL,email TEXT UNIQUE NOT NULL,nome TEXT NOT NULL,telefone TEXT,perfil perfil_usuario NOT NULL DEFAULT 'paciente',ativo BOOLEAN NOT NULL DEFAULT TRUE,criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_usuarios_firebase_uid ON usuarios(firebase_uid);
CREATE INDEX idx_usuarios_email ON usuarios(email);
CREATE INDEX idx_usuarios_nome_trgm ON usuarios USING GIN(nome gin_trgm_ops);
CREATE TABLE pacientes(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),usuario_id UUID NOT NULL UNIQUE REFERENCES usuarios(id) ON DELETE CASCADE,cpf TEXT UNIQUE NOT NULL,data_nascimento DATE NOT NULL,sexo sexo,endereco TEXT,cidade TEXT,estado CHAR(2),cep TEXT,plano_saude TEXT,numero_plano TEXT,observacoes TEXT,criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_pacientes_cpf ON pacientes(cpf);
CREATE INDEX idx_pacientes_usuario ON pacientes(usuario_id);
CREATE TABLE especialidades(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),nome TEXT NOT NULL UNIQUE,ativo BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE medicos(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),usuario_id UUID NOT NULL UNIQUE REFERENCES usuarios(id) ON DELETE CASCADE,crm TEXT NOT NULL UNIQUE,especialidade_id UUID REFERENCES especialidades(id),bio TEXT,ativo BOOLEAN NOT NULL DEFAULT TRUE,criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_medicos_especialidade ON medicos(especialidade_id);
CREATE TABLE horarios_disponiveis(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),medico_id UUID NOT NULL REFERENCES medicos(id) ON DELETE CASCADE,dia_semana SMALLINT NOT NULL CHECK(dia_semana BETWEEN 0 AND 6),hora_inicio TIME NOT NULL,hora_fim TIME NOT NULL,duracao_min SMALLINT NOT NULL DEFAULT 30,ativo BOOLEAN NOT NULL DEFAULT TRUE,CHECK(hora_fim>hora_inicio));
CREATE INDEX idx_horarios_medico ON horarios_disponiveis(medico_id,dia_semana);
CREATE TABLE bloqueios_agenda(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),medico_id UUID NOT NULL REFERENCES medicos(id) ON DELETE CASCADE,data_inicio TIMESTAMPTZ NOT NULL,data_fim TIMESTAMPTZ NOT NULL,motivo TEXT,CHECK(data_fim>data_inicio));
CREATE INDEX idx_bloqueios_medico_data ON bloqueios_agenda(medico_id,data_inicio,data_fim);
CREATE TABLE agendamentos(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),paciente_id UUID NOT NULL REFERENCES pacientes(id),medico_id UUID NOT NULL REFERENCES medicos(id),data_hora TIMESTAMPTZ NOT NULL,duracao_min SMALLINT NOT NULL DEFAULT 30,status status_agendamento NOT NULL DEFAULT 'pendente',tipo TEXT NOT NULL DEFAULT 'consulta',observacoes TEXT,criado_por UUID REFERENCES usuarios(id),cancelado_por UUID REFERENCES usuarios(id),motivo_cancelamento TEXT,criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),CONSTRAINT uq_medico_horario UNIQUE(medico_id,data_hora));
CREATE INDEX idx_agendamentos_paciente ON agendamentos(paciente_id,data_hora DESC);
CREATE INDEX idx_agendamentos_medico ON agendamentos(medico_id,data_hora);
CREATE INDEX idx_agendamentos_status ON agendamentos(status);
CREATE INDEX idx_agendamentos_data ON agendamentos(data_hora);
CREATE TABLE tipos_exame(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),nome TEXT NOT NULL,descricao TEXT,preparo TEXT,ativo BOOLEAN NOT NULL DEFAULT TRUE);
CREATE TABLE exames(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),paciente_id UUID NOT NULL REFERENCES pacientes(id),tipo_exame_id UUID REFERENCES tipos_exame(id),agendamento_id UUID REFERENCES agendamentos(id),medico_id UUID REFERENCES medicos(id),status status_exame NOT NULL DEFAULT 'solicitado',data_solicitacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),data_coleta TIMESTAMPTZ,data_resultado TIMESTAMPTZ,arquivo_url TEXT,arquivo_nome TEXT,observacoes TEXT,criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_exames_paciente ON exames(paciente_id,criado_em DESC);
CREATE INDEX idx_exames_status ON exames(status);
CREATE INDEX idx_exames_medico ON exames(medico_id);
CREATE TABLE notificacoes(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,tipo tipo_notificacao NOT NULL,status status_notificacao NOT NULL DEFAULT 'pendente',titulo TEXT,mensagem TEXT NOT NULL,referencia_id UUID,referencia_tipo TEXT,tentativas SMALLINT NOT NULL DEFAULT 0,enviada_em TIMESTAMPTZ,erro TEXT,criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_notificacoes_usuario ON notificacoes(usuario_id,criado_em DESC);
CREATE INDEX idx_notificacoes_status ON notificacoes(status);
CREATE TABLE tokens_push(id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,token TEXT NOT NULL UNIQUE,plataforma TEXT NOT NULL,ativo BOOLEAN NOT NULL DEFAULT TRUE,criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_tokens_usuario ON tokens_push(usuario_id) WHERE ativo=TRUE;
CREATE TABLE logs_acesso(id BIGSERIAL PRIMARY KEY,usuario_id UUID REFERENCES usuarios(id),acao TEXT NOT NULL,recurso TEXT,ip TEXT,user_agent TEXT,criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX idx_logs_usuario ON logs_acesso(usuario_id,criado_em DESC);
CREATE INDEX idx_logs_data ON logs_acesso(criado_em DESC);
CREATE OR REPLACE FUNCTION trigger_set_atualizado_em() RETURNS TRIGGER AS $$ BEGIN NEW.atualizado_em=NOW();RETURN NEW;END;$$ LANGUAGE plpgsql;
CREATE TRIGGER set_atualizado_em_usuarios BEFORE UPDATE ON usuarios FOR EACH ROW EXECUTE FUNCTION trigger_set_atualizado_em();
CREATE TRIGGER set_atualizado_em_pacientes BEFORE UPDATE ON pacientes FOR EACH ROW EXECUTE FUNCTION trigger_set_atualizado_em();
CREATE TRIGGER set_atualizado_em_agendamentos BEFORE UPDATE ON agendamentos FOR EACH ROW EXECUTE FUNCTION trigger_set_atualizado_em();
CREATE TRIGGER set_atualizado_em_exames BEFORE UPDATE ON exames FOR EACH ROW EXECUTE FUNCTION trigger_set_atualizado_em();
INSERT INTO especialidades(nome) VALUES('Clinico Geral'),('Cardiologia'),('Dermatologia'),('Ortopedia'),('Ginecologia'),('Pediatria'),('Neurologia'),('Oftalmologia');
INSERT INTO tipos_exame(nome,descricao,preparo) VALUES('Hemograma Completo','Analise das celulas do sangue','Jejum de 8 horas'),('Glicemia em Jejum','Nivel de glicose no sangue','Jejum de 12 horas'),('Colesterol e Triglicerides','Perfil lipidico completo','Jejum de 12 horas'),('Eletrocardiograma (ECG)','Atividade eletrica do coracao','Nenhum preparo necessario'),('Raio-X de Torax','Imagem do pulmao e coracao','Retirar adornos metalicos'),('Ultrassom Abdominal','Imagem dos orgaos abdominais','Jejum de 6 horas'),('TSH / T4 Livre','Funcao da tireoide','Jejum de 4 horas'),('Urina Tipo I (EAS)','Analise de urina','Primeira urina da manha');
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE pacientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE agendamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE exames ENABLE ROW LEVEL SECURITY;
ALTER TABLE notificacoes ENABLE ROW LEVEL SECURITY;